# Generated by Django 4.1.1 on 2022-09-21 11:27

from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, validators=[core.validators.valid_email_domains]),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
