# Generated by Django 4.1.1 on 2022-09-29 10:50

import datetime
import django.core.validators
from django.db import migrations, models
import teachers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name_column', max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"first_name" field less than two symbols')], verbose_name='first name')),
                ('last_name', models.CharField(db_column='last_name_column', error_messages={'min_length': '"last_name" field less than two symbols'}, max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last_name')),
                ('job', models.CharField(db_column='job_column', max_length=100, verbose_name='job')),
                ('birthday', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('email', models.EmailField(max_length=254, validators=[teachers.validators.ValidEmailDomain('@gmail.com', '@yahoo.com', '@test.com', '@icloud.com', '@tenet.com'), teachers.validators.validate_unique_email])),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
