# Generated by Django 4.1.1 on 2022-09-21 11:49

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='group_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"group_name" field less than two symbols')], verbose_name='group name')),
                ('group_start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('group_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
