# Generated by Django 4.1.1 on 2022-10-08 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_group_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='group_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
    ]
